enabled: true
filter_words:
  - "cnm"
  - "孙笑川"
  - "傻逼"
  - "傻B"
  - "sb"
  - "叛徒"
  - "特务"
filter_rules:
  regex:
    - "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}(?:\\.[a-zA-Z]{2,})?"
  interference_characters:
    - '/'
    - '\'
    - '.'
  replace:
    replace_words:
      - "喵"

warning:
  enabled: true
  message: "§c不要发布敏感信息!"