enabled: true
filter_level: 1
filter_words:
  - "cnm"
  - "孙笑川"
  - "傻逼"
  - "傻B"
  - "sb"
  - "叛徒"
  - "特务"
filter_rules:
  regex:
    - "\\d+"
  interference_characters:
    - '/'
    - '\'
    - '.'
  ngram:
    enable_ngram: true
    n: 2
    words:
      - "喵呜~"
      - "喵呜"
      - "喵"
      - "呜"
  replace:
    replace_words:
      - "喵"
      - "*"

warning:
  enabled: true
  message: "&c请勿发布敏感信息!"